# Makefile

# Define variables
DOCKER_COMPOSE = docker-compose

# Default target (run the app)
all: up

# Bring up the containers
up:
	$(DOCKER_COMPOSE) up -d

# Stop and remove the containers
down:
	$(DOCKER_COMPOSE) down

# Rebuild the containers
build:
	$(DOCKER_COMPOSE) build

